name: CI/CD - Ansible Playbook for WSL

on:
  push:
    branches:
      - main  # Or your desired branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up SSH keys
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }} # Store your private SSH key in GitHub Secrets

    - name: Run Ansible Playbook on WSL
      run: |
        ansible-playbook -i "172.29.154.116/20," --user=chandrababu --private-key=$HOME/.ssh/id_rsa playbook.yml
