# .github/workflows/ci-cd.yml
name: Ansible Playbook Execution

on:
  push:
    branches:
      - main  # Or the branch where you want to trigger CI/CD

jobs:
  ansible:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Ansible
      uses: shivammathur/setup-ansible@v2

    - name: Run Ansible Playbook
      run: |
        ansible-playbook ansible.yml
